### ISSUE TITLE
Refactoring of golem-gasless-server: Step #1

### ISSUE THREAD

**Issue by golmek** [golemfactory/polygon-gasless-server#4]
One of the paths in Onboarding Portal, will require Relay Server to put user MetaTx on Blockchain -> GLM == TRUE, Native == FALSE path

For that goal we will reuse already developer gasless server, which was used for Throg: https://github.com/golemfactory/polygon-gasless-server

**Acceptance Criteria:**
- Refactor golem-gasless-server
  - Rewrite to NodeJs
- Server has to suppor Allowance MetaTx
- Server should have a functionality to verify a MetaTx before Relaying it
  - For instance relay only Allowance Tx for GLM tokens  
- Create new Repo

**Prerequisite:**
- https://github.com/golemfactory/golem-internal/issues/662

**Additional Information**
- Onboarding Portal flow diagram: https://www.notion.so/golemnetwork/User-Flow-8bac24aab7f8433280b8ead0f89f7a4c?pvs=4

**Comment by pociej** [comment]
For now https://github.com/golemfactory/polygon-gasless-server/tree/feature/approve_support on separated branch is created and working. It accepts allowances. Refactoring to Node and moving to new repo will be done later if ever ( maybe it wont be needed).

**Comment by golmek** [comment]
**DONE:**
- Separate branch created: https://github.com/golemfactory/polygon-gasless-server/tree/feature/approve_support
- Allowance Added
- Still works on Deno (not re-written to nodeJs)

**TO DO:**
- Make decision if we want to re-write it in node:  https://github.com/golemfactory/polygon-gasless-server/issues/5
